### ISSUE TITLE
releaseモードのAndroidアプリでClientExceptionが発生する

### ISSUE THREAD

**Issue by fujidaiti** [fujidaiti/yumemi-flutter-codecheck#8]
実行端末はRedmi Note 9Sです。

```shell
$ flutter devices

4 connected devices:

Redmi Note 9S (mobile) • 50887fe5                             • android-arm64  • Android 11 (API 30)
iPhone 14 Pro (mobile) • 3D0DF457-008A-4A9E-8A42-F70489F0F2B2 • ios            •
com.apple.CoreSimulator.SimRuntime.iOS-16-4 (simulator)
macOS (desktop)        • macos                                • darwin-arm64   • macOS 13.4 22F66
darwin-arm64
Chrome (web)           • chrome                               • web-javascript • Google Chrome 114.0.5735.198

No wireless devices were found.
```

ビルド

```shell
$ makers run -d 50887fe5 --release

[cargo-make] INFO - makers 0.36.11
[cargo-make] INFO - Build File: Makefile.toml
[cargo-make] INFO - Task: run
[cargo-make] INFO - Profile: development
[cargo-make] INFO - Running Task: legacy-migration
[cargo-make] INFO - Running Task: runner
Deprecated. Use `dart run` instead.
[INFO] Generating build script completed, took 178ms
[INFO] Reading cached asset graph completed, took 27ms
[INFO] Checking for updates since last build completed, took 297ms
[INFO] Running build completed, took 4ms
[INFO] Caching finalized dependency graph completed, took 14ms
[INFO] Succeeded after 22ms with 0 outputs (0 actions)
[cargo-make] INFO - Running Task: run
Launching lib/main.dart on Redmi Note 9S in release mode...
Running Gradle task 'assembleRelease'...                         2,291ms
✓  Built build/app/outputs/flutter-apk/app-release.apk (7.5MB).
Installing build/app/outputs/flutter-apk/app-release.apk...      2,535ms

Flutter run key commands.
h List all available interactive commands.
c Clear the screen
q Quit (terminate the application on the device).
I/flutter (21924): ClientException with SocketException: Failed host lookup: 'api.github.com' (OS Error: No address associated with hostname, errno = 7), uri=https://api.github.com/search/repositories?q=go&page=0&per_page=30
I/flutter (21924): UnimplementedError: 検索画面でのエラー表示
I/flutter (21924): #0      Search.build.<anonymous closure> (package:yumemi_flutter_codecheck/screens/search.dart:47)
I/flutter (21924): #1      RepositoryOverviewList.build.<anonymous closure> (package:yumemi_flutter_codecheck/components/github/repository_overview_list.dart:33)
I/flutter (21924): #2      AsyncValueX.when (package:riverpod/src/common.dart:679)
I/flutter (21924): #3      RepositoryOverviewList.build (package:yumemi_flutter_codecheck/components/github/repository_overview_list.dart:29)
I/flutter (21924): #4      _ConsumerState.build (package:flutter_riverpod/src/consumer.dart:479)
I/flutter (21924): #5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5198)
I/flutter (21924): #6      ConsumerStatefulElement.build (package:flutter_riverpod/src/consumer.dart:542)
I/flutter (21924): #7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5086)
I/flutter (21924): #8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5251)
I/flutter (21924): #9      Element.rebuild (package:flutter/src/widgets/framework.dart:4805)
I/flutter (21924): #10     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2780)
I/flutter (21924): #11     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:903)
I/flutter (21924): #12     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:358)
I/flutter (21924): #13     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1284)
I/flutter (21924): #14     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1214)
I/flutter (21924): #15     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1072)
I/flutter (21924): #16     _invoke (dart:ui/hooks.dart:142)
I/flutter (21924): #17     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:359)
I/flutter (21924): #18     _drawFrame (dart:ui/hooks.dart:112)
```

**Comment by fujidaiti** [comment]
`AndroidManifest.xml`に権限の追加が必要です。

https://docs.flutter.dev/data-and-backend/networking
